[build]
# Build configuration options

[target.'cfg(all())']
rustflags = [
    # Allow standard rustc lints
    "-A", "dead_code",
    "-A", "unused_imports",
    "-A", "unused_variables",
    # Allow clippy-specific lints
    "-A", "clippy::field_reassign_with_default",
    "-A", "clippy::manual_clamp",
    "-A", "clippy::needless_range_loop",
    "-A", "clippy::approx_constant",
]
