# rustfmt configuration for Veritas Nexus
# This configuration ensures consistent code formatting across the project

# Basic formatting
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import formatting
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"
imports_indent = "Block"
imports_layout = "Vertical"

# Function and method formatting
fn_params_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
fn_single_line = false
where_single_line = false

# Type and trait formatting
type_punctuation_density = "Wide"
use_small_heuristics = "Default"
indent_style = "Block"

# Comments and documentation
comment_width = 80
doc_comment_code_block_width = 80
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
format_doc_comments = true

# String formatting
format_strings = true
format_macro_matchers = true
format_macro_bodies = true

# Struct and enum formatting
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
struct_lit_single_line = true
empty_item_single_line = true

# Array and slice formatting
array_width = 60
chain_width = 60

# Expression formatting
spaces_around_ranges = false
binop_separator = "Front"
combine_control_expr = true
condense_wildcard_suffixes = false
force_explicit_abi = true
format_code_in_doc_comments = true

# Match formatting
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false

# Module formatting
module_width = 100
newline_style = "Unix"
remove_nested_parens = true

# Error handling
error_on_line_overflow = false
error_on_unformatted = false

# Blank lines
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0

# Trailing elements
trailing_comma = "Vertical"
trailing_semicolon = true

# Miscellaneous
format_generated = true
skip_children = false
hide_parse_errors = false
color = "Auto"
required_version = "1.7.0"

# Unstable features (commented out for stability)
# These can be enabled when using nightly rustfmt
# unstable_features = true
# format_code_in_doc_comments = true
# overflow_delimited_expr = true
# group_imports = "StdExternalCrate"
# hex_literal_case = "Upper"